### ISSUE TITLE
Search widget not working

### ISSUE THREAD

**Issue by nicofrand** [Qwant/MobileApp#1]
It seems it now uses Firefox for android as engine and thus uses its search widget.

But this widget is broken (the search does not return anything) and obsolete: see https://bugzilla.mozilla.org/show_bug.cgi?id=1131087

**Comment by p-bertran** [comment]
Thanks for your report.
We are aware of this issue and indeed the widget sometimes doesn't return results. We are working on it.

**Comment by nicofrand** [comment]
Hi, any news regarding this issue ? It **never** return any result.

**Comment by p-bertran** [comment]
Hi,
This widget will be completely removed in the next update, and replaced by a new one.
This update should be available very soon as a RC is in testing at the moment

**Comment by nicofrand** [comment]
Can I test it too ? Thanks for the work and answer !


Le 2 févr. 2018 11:16, p-bertran <notifications@github.com> a écrit :

Hi,
This widget will be completely removed in the next update, and replaced by a new one.
This update should be available very soon as a RC is in testing at the moment

**Comment by p-bertran** [comment]
Fixed. New widget needs more functionnality, but it works now

**Comment by p-bertran** [comment]
Yes, that's what I mean by "new widget", but you're right it's a shortcut to newtab. And as I said it needs more functionalities (like a dedicated activity with suggestions). It's in our todo list, but sorry to say not a priority right now.
I'll keep you informed.

**Comment by nicofrand** [comment]
Is there a public roadmap available somewhere? I don't use Qwant on mobile because of that (and other things) :/
